modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "ftbt_offline_fix"
version = "${version}"
displayName = "FTBT Offline Fix"
authors = "Terry_MC, Star Carefree"
description = '''
A really simple client-side mod that fix the offline bug of FTB Teams.
'''
logoFile = "icon.png"

[[dependencies.ftbt_offline_fix]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbt_offline_fix]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbt_offline_fix]]
modId = "architectury"
type = "required"
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbt_offline_fix]]
modId = "ftbteams"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ftbt_offline_fix.mixins.json"
